### ISSUE TITLE
Node stops (or pauses) accepting transactions

### ISSUE THREAD

**Issue by Tom-MUC** [input-output-hk/shelley-testnet#13] opened 2019-06-22 16:43 UTC
**Describe the bug**
After the jormungandr has been started it accepts a first transaction using the script "faucet-send-money.sh".  After using the same script a second time with same destination address the node no longer accepts any transaction for a while. 

**To Reproduce**
(The behavior appears to show up only sometimes, not always)
1. Start jormungandr
2. faucet-send-money.sh ADDRESS AMOUNT
3. Wait until transaction is part of a block (status: InABlock), but do not wait more than a few seconds
4. faucet-send-money.sh SAME_ADDRESS_AS_ABOVE DIFFERENT_AMOUNT
5. Check node stats using "node stats get", the txRecvCnt is 1 instead of 2 and the node also stopped making blocks

**Expected behavior**
The node to accept more than 1 transaction.

**Additional context**
Installed release "jormungandr-v0.2.2-armv7-unknown-linux-gnueabihf.tar.gz"
Operating System: Ubuntu 16.04.5 LTS
Kernel: Linux 4.14.28-124
Architecture: arm

**Comment by vincenthz** [comment] 2019-06-23 14:03
Thanks for the report, looks like it's a duplicate of #10

**Comment by gmanroney** [comment] 2019-06-24 13:18
DUPLICATE

**Closed by gmanroney** 2019-06-24 13:18 UTC
