### ISSUE TITLE
'entered unreachable code' spotted while running passive node

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/shelley-testnet#73] opened 2019-09-30 12:23 UTC
Running latest master release build just before 0.5.3 was tagged.
Passive node, with public address set in the node config.

Spotted this error in node output:

Sep 30 22:06:25.563 INFO incoming P2P connection on 10.1.1.240:3100, peer_addr: 103.94.50.247:43184, task: network
Sep 30 22:06:46.664 INFO peer responded with different node id: 401510887185635334, node_id: 401510887185635334, peer_addr: 138.68.122.238:3000, task: network
thread 'tokio-runtime-worker-5' panicked at 'internal error: entered unreachable code', /Users/gregberesnev/.cargo/registry/src/github.com-1ecc6299db9ec823/poldercast-0.7.0/src/topology/ring.rs:74:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by dorin100** [comment] 2019-09-30 14:25
this seems a duplicate of https://github.com/input-output-hk/jormungandr/issues/813

**Comment by dorin100** [comment] 2019-10-01 09:59
Hi @hodlonaut . It seems that 0.5.3 had some issues. Can you please try to use 0.5.4? Thanks.

**Comment by hodlonaut** [comment] 2019-10-01 10:20
> Hi @hodlonaut . It seems that 0.5.3 had some issues. Can you please try to use 0.5.4 and see if it is reproducible? Thanks.

Thanks, I'm already using 0.5.4. There is a decent amount of things being logged e.g.

Oct 01 20:14:56.946 INFO incoming P2P connection on 10.1.1.240:3110, peer_addr: 122.199.42.20:47320, task: network


Oct 01 20:18:40.494 INFO fragment subscription stream failure: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } }, sub_task: server, task: network
Oct 01 20:18:40.494 INFO gossip subscription stream failure: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } }, sub_task: server, task: network
Oct 01 20:18:40.494 INFO block subscription stream failure: Error { code: Unknown, source: Status { code: Unknown, message: "h2 protocol error: broken pipe" } }, sub_task: server, task: network

but the lastBlockHeight seemingly remains unchanged.

**Comment by dorin100** [comment] 2019-10-01 10:22
Yeap. I am affected by the same issue, tracked here - https://github.com/input-output-hk/jormungandr/issues/860

Can we close this one considering the actual functionality?

**Comment by hodlonaut** [comment] 2019-10-01 10:25
If you feel it's been addressed, sure, go ahead. I had no reliable steps to reproduce that 'unreachable code' issue, I just thought I'd raise a ticket in case the error message made more sense to the IOHK developers

**Comment by dorin100** [comment] 2019-10-01 10:28
Ok. I will close it for the moment. Please let us know (by reopening this issue or by creating a new one) if you will see the issue again.

We are investigating #860 with priority.

**Closed by dorin100** 2019-10-01 10:28 UTC
Labels: duplicate
