### ISSUE TITLE
Unable to get funds from Faucet

### ISSUE THREAD

**Issue by JSCSJSCS** [input-output-hk/shelley-testnet#109] opened 2019-10-10 04:11 UTC
** Prerequisites information
Operating System: Windows 10 Home build 1903 64bit
Intel I7-9750H CPU @2.6GHz, 16GB RAM

```
jcli 0.5.6 (HEAD-7ab929ea+, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jormungandr 0.5.6 (HEAD-7ab929ea+, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

Installed using jormungandr-v0.5.6-x86_64-pc-windows-gnu.zip
```

**Describe the bug
After creating a new address (both with createAddress.sh and manually, the generated address is entered to the input at https://testnet.iohkdev.io/shelley/tools/faucet/. I have treid using Brave and Chrome browsers.

After Request is clicked, the input area and request button are no longer visible and there is no new output. Some other issues reported the page said how many ADA were being sent. I did not get this indication. I have tried 4 different addresses and none of them have received funds.

They are:
ca1s58jpdnswa40403gc7690654nap5rng5v2zpv3pgd59mzsns562mkervjrr
ca1sk3aj54u0jh926adru453u0c0sln46pq06qdtsd4cf0e0fhzppxawdwhqx6
ca1s4txv29we0y8sa9etx8qyewgqhv329u84q6unkrt93semsue904yxktn0am
ca1shv773wfvh9cgasg86u6def27dexf67w6qmuc4ve36pj7lh3f63p2dt40qc

Other testnet participants in the telegram group have also tried sending ADA to the first address above. These were never received. The output of the account get is as follows.

```
$ ./jcli rest v0 account get ca1s58jpdnswa40403gc7690654nap5rng5v2zpv3pgd59mzsns562mkervjrr -h  http://127.0.0.1:3101/api
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3101/api/v0/account/0f20b670776afabe28c7b457ea959f4341cd1462841644286d0bb14270a695bb: Client Error: 404 Not Found

```
Other testnet participants get the same output on their nodes.

Other information:
One telegram testnet user tried to send the first address above some ADA. Their output included:
```
- fragment_id: 3d19d260935c0138313560003e4a8d27140461d0fbaef51c75bb22f5fef82e5f
  last_updated_at: "2019-10-10T01:33:24.628045+00:00"
  received_at: "2019-10-10T01:30:11.860031+00:00"
  received_from: Rest
  status:
    InABlock:
      date: "229.31795"

```
These funds also never arrived. 
```
$ ./jcli rest v0 account get ca1s58jpdnswa40403gc7690654nap5rng5v2zpv3pgd59mzsns562mkervjrr -h  http://127.0.0.1:3101/api
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3101/api/v0/account/0f20b670776afabe28c7b457ea959f4341cd1462841644286d0bb14270a695bb: Client Error: 404 Not Found

```

My node is syncing albeit with some lag as others are reporting (#860), but blocks are being applied and have passed those of reported transactions above, so my node should include the transaction it is assumed.

```
PS D:\jormungandr-node> ./jcli rest v0 node stats get --host "http://127.0.0.1:3101/api"
---
blockRecvCnt: 193606
lastBlockDate: "229.34950"
lastBlockFees: 0
lastBlockHash: 1968cfded9e068ce8f5631ebf5ce8407868d14fc09c65a56308842b1666e09f7
lastBlockHeight: "85607"
lastBlockSum: 0
lastBlockTime: "2019-10-10T03:19:34+00:00"
lastBlockTx: 0
txRecvCnt: 8
uptime: 15543

```

**To Reproduce
1. Create an address using createAddress.sh or manually.
2. Enter the address in the faucet web page.
3. Click request.
4. No ADA ever arrives.

**Expected behavior
I expected after about 10-15 minutes to see the funds in the address.
I expected others to send my address a transaction and that be received as well.

node-config.yaml

```
storage: "D:/jormungandr-node/storage/"  #This is not shown in the Windows section of the how-to
log:
  format: plain
  level: info
  output: stderr
p2p:
#  listen_address: /ip4/0.0.0.0/tcp/3000
  listen_address: /ip4/192.168.1.8/tcp/3000  #Local NAT IP Address because 0.0.0.0 created tremendous blocks applied lags by hours sometimes
#  listen_address: /ip4/127.0.0.1/tcp/3000
  
  public_address: /ip4/publicIPaddress/tcp/3000
  topics_of_interest:
    blocks: high
    messages: high
  trusted_peers: [/ip4/3.123.177.192/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]
rest:
  listen: "127.0.0.1:3101"
```

**Comment by carl-IOHK** [comment] 2019-10-10 14:40
Hi JSCSJSCS the faucet seems to be working better today but it goes up and down as it is affected by the general stability of the network. We are aware and are working in it. I belive that this is caused by https://github.com/input-output-hk/jormungandr/issues/860

**Comment by carl-IOHK** [comment] 2019-10-11 17:24
@JSCSJSCS would you mind if we move this issue to the Support Portal? That way we can link it to the root casue issue and keep track of it better. To do that you could create a ticket here https://iohk.zendesk.com/hc/en-us/requests/new and drop note in this ticket with the ticket number. I would do it for you but I cannot since I do not have your email address.

**Comment by JSCSJSCS** [comment] 2019-10-11 17:34
Done.
https://iohk.zendesk.com/hc/en-us/requests/71734

**Comment by carl-IOHK** [comment] 2019-10-15 13:33
Thanks @JSCSJSCS for opening a ticket in https://iohk.zendesk.com/hc/en-us/requests/new  we will close this one.

**Closed** 2019-10-15 13:34 UTC
Labels: duplicate
