### ISSUE TITLE
Error accepting connection: Too many open files (os error 24), scope: global

### ISSUE THREAD

**Issue by Dmindfuse** [input-output-hk/shelley-testnet#107] opened 2019-10-09 18:16 UTC
**Describe the bug
I get the error message in the title appear frequently in the log. Following the error, at a later stage, this is followed by WARNings that indicate stream issues. I'm not sure if this requires a follow-up/bug because the node continues to sync despite the errors.

** Prerequisites information
1. `jcli --full-version` output;
jcli 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

1. `jormungandr --full-version` output;
jormungandr 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

1. What is your Operating system?
Linux Mint

1. What version of the jormungandr node are you using?
0.5.6

1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)?
.tar.gz unpack

**To Reproduce
Run jormungandr

**Expected behavior
No error, no WARN regarding stream processing.

**Additional context
```
Oct 09 20:11:56.945 WARN error while streaming response: Error { code: Internal, cause: CannotIterate }, node_id: 131986773828746483, peer_addr: 35.228.32.60:3100, task: network
Oct 09 20:11:56.945 INFO UploadBlocks request failed: Error { code: Internal, source: Status { code: Internal, message: "h2 protocol error: protocol error: unexpected internal error encountered" } }, node_id: 131986773828746483, peer_addr: 35.228.32.60:3100, task: network
Oct 09 20:11:56.947 WARN error while streaming response: Error { code: Internal, cause: CannotIterate }, node_id: 16519382088092967150, peer_addr: 79.160.102.242:3100, task: netw
```

If this is not an issue, please go ahead and close this.

**Comment by rdlrt** [comment] 2019-10-10 03:05
Duplicate of Issue #83

**Closed** 2019-10-10 10:02 UTC
Labels: duplicate
