### ISSUE TITLE
Clear instructions on how to use boostrap script missing 

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#77] opened 2019-09-30 20:02 UTC
**Describe the bug**
Issue 12. 
If you use bootstrap script you can expect the following results:

Why would we say "if you use bootstrap" when that was part of the instructions? This is confusing for CP

**To Reproduce**
1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. Find If you use bootstrap script you can expect the following results:

**Expected behavior**
A clear and concise description of what the user is expected to do.

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by dorin100** [comment] 2019-10-02 07:10
This might be a duplicate of https://github.com/input-output-hk/shelley-testnet/issues/72

We don't use `bootstrap sctipt` anymore.

**Comment by jakewyo** [comment] 2019-10-08 18:17
@dorin100 this can be closed per our discussion on Slack.

Thanks!

**Closed** 2019-10-09 04:34 UTC
Labels: documentation, duplicate
