### ISSUE TITLE
Move info about technical opperatons to developer-centric instruction set.

### ISSUE THREAD

**Issue by carl-IOHK** [input-output-hk/shelley-testnet#75] opened 2019-09-30 19:52 UTC
**Describe the bug**
Issue 10.
If you want to create several nodes or stake pools, or implement and test more complex configurations, you can use a Nix script that wraps some of the functions into a one-step process for ease of use. This script bundles the node installation and provides a way to easily vary the configuration from the command line, without any file edition.
This should be in the How to install Jörmungandr from source: section since it leads to some very technical stuff. 

**To Reproduce**
1. Go to the page
https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/
2. Find the If you want to create several nodes or stake pools... instructions. 

**Expected behavior**
Move these instructions to the **How to install Jörmungandr from source**: section

**Additional context**
Context is a non-technical user trying to get involved in and learn about Shelley Networked Testnet; CP = Common Person (i.e. a regular non-technical user)

**Comment by dorin100** [comment] 2019-10-02 07:11
`get-started/setting-up-the-self-node/` needs to be updated as it is not actual anymore.

**Comment by dorin100** [comment] 2019-10-03 07:14
duplicate of https://github.com/input-output-hk/shelley-testnet/issues/72

**Comment by jakewyo** [comment] 2019-10-08 18:18
@dorin100 this can be closed per our discussion on Slack.

Thanks!

**Closed** 2019-10-09 04:34 UTC
Labels: documentation, duplicate
