### ISSUE TITLE
Getting stream failures

### ISSUE THREAD

**Issue by embraceitandfaceit** [input-output-hk/shelley-testnet#83] opened 2019-10-01 06:23 UTC
I get stream failure in the logs of my node. Any idea what might cause this issue and how I could resolve it? Thank you

![image](https://user-images.githubusercontent.com/55874818/65938915-a59d0f00-e424-11e9-9e28-4c3c9324c5bf.png)

Calling for node stats works, it has been running for +12 hours now

![image](https://user-images.githubusercontent.com/55874818/65938957-c36a7400-e424-11e9-8056-bb33c44cd70b.png)

**Comment by dorin100** [comment] 2019-10-01 09:56
Hi @embraceitandfaceit . This is a duplicate of https://github.com/input-output-hk/jormungandr/issues/860

Check this post - https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60 - for some details about your stats.

**Comment by embraceitandfaceit** [comment] 2019-10-01 18:22
I don't understand, what should I do please. I'm not a technically savy person.

**Comment by dorin100** [comment] 2019-10-02 07:30
I updated https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60 with some steps. 

In the meantime, we are working on fixing issues and stabilizing the nodes.

**Comment by cliffc2** [comment] 2019-10-07 23:56
Oct 08 07:37:29.342 INFO client P2P connection closed, node_id: 580648938712873299, peer_addr: 213.74.231.20:3333, task: network
Oct 08 07:37:29.347 WARN response canceled by the processing task, node_id: 4485365775303479996, peer_addr: 3.123.155.47:3000, task: network
Oct 08 07:37:29.347 WARN pulled block validation failed: Error { code: Unavailable, source: Error { code: Unavailable, cause: Canceled } }, node_id: 4485365775303479996, peer_addr: 3.123.155.47:3000, task: network
failed to open /dev/urandom: Os { code: 24, kind: Other, message: "Too many open files" }
thread 'leadership0' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5

**Comment by rdlrt** [comment] 2019-10-08 01:51
@cliffc2 different issue, wouldn't belong here. But you need to increase ulimit on your system (can do at session level, but best to update system settings so that you dont miss it next time). Anything below 2048 for nofiles would be asking for trouble, you'd want to keep some buffer from future perspective. I use 20480 on mine (but my use case is different).

**Comment by jakewyo** [comment] 2019-10-08 16:12
Hi @embraceitandfaceit you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by dorin100** [comment] 2019-10-11 13:17
We are moving to Zendesk for support. Closing this issue as we already tracking it here - https://github.com/input-output-hk/jormungandr/issues/860

**Closed by dorin100** 2019-10-11 13:17 UTC
Labels: duplicate
