### ISSUE TITLE
error: building the genesis block

### ISSUE THREAD

**Issue by lsc3** [input-output-hk/shelley-testnet#15] opened 2019-06-22 23:29 UTC
**Describe the bug**
When installing jomungandr get:
"error: building the genesis block"

Below is output of bootstrap.sh script with error msg ....

mycomputer$ ./bootstrap.sh 
########################################################

* Consensus: genesis_praos
* REST Port: 8443
* Slot duration: 10

########################################################

* CLI version: jcli 0.2.2
* NODE version: jormungandr 0.2.2

########################################################

genesis file corrupted
  |-> blockchain_configuration.block0_consensus: Matching variant not found at line 14 column 21
error: building the genesis block

**To Reproduce**

Not sure how others can reproduce. Installed jormungandr per intstructions ...
https://www.youtube.com/watch?v=hvlme_E0Lvg&list=PLnPTB0CuBOBzHmIMplX6BT6F3tzKOSFG5&index=8&t=0s

**Expected behavior**
Running node

**Additional context**
I tried re-downloading and extracting the binary several times. But same issue each time.
Jormungandr binary used:
(https://github.com/input-output-hk/jormungandr/releases/download/v0.2.2/jormungandr-v0.2.2-x86_64-apple-darwin.tar.gz).

Computer:
 Mac-mini (late 2014) with MacOS Mojave 10.14.5. 8Gb Ram, 875Gb free disk space.

Not sure if this is correct forum for this. Any help greatly appreciated.

**Comment by jbgi** [comment] 2019-06-23 06:57
The issue is that some (incompatible) changes have happen on the master branch of https://github.com/input-output-hk/jormungandr/ since the `0.2.2` release. The instruction should be have been to download the `bootstrap` script from the tag corresponding to the release you use.
Can you retry using the `bootstrap` script from https://github.com/input-output-hk/jormungandr/tree/v0.2.2/scripts ?

**Comment by vincenthz** [comment] 2019-06-23 16:45
fixed by making a 0.2.3 although it's fixed also by using 0.2.2 scripts as @jbgi mentioned.

**Comment by lsc3** [comment] 2019-06-23 17:08
Worked!
Thank you!

**Comment by lsc3** [comment] 2019-06-23 17:09
Worked!
Thank you.

**Closed** 2019-06-23 17:11 UTC
