### ISSUE TITLE
Error occurred during request handling: Account does not exist, scope: global

### ISSUE THREAD

**Issue by oceanrascal** [input-output-hk/shelley-testnet#56] opened 2019-09-28 20:15 UTC
**Describe the bug**
First of all, CONGRATULATIONS FOR RELEASING THE ADA TESTNET.
I installed the test node on a Debian dedicated server. It runs fine. I installed everything according to the guide  'How to setup a Jormungandr Networking node (v 0.5.0)' by Samuel Leathers. 

The faucet then sends me the test funds. The error occurs when I try to verify the transaction by calling the API.

./jcli rest v0 account get $(cat receiver_account.txt) -h  http://127.0.0.1:3101/api

I get the following error:
WARN Error occurred during request handling: Account does not exist, scope: global
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3101/api/v0/account/7de59db5e5e799f19123275f8aaee1fa53b66e1a10b6601c5e86345280e9b52d: Client Error: 404 Not Found

Ports are open and API is callable. What does WORK FINE are calls like :
./jcli rest v0 message logs -h http://127.0.0.1:3101/api
or
curl http://127.0.0.1:3101/api/v0/node/stats
or
./jcli rest v0 node stats get -h "http://127.0.0.1:3101/api"

**Expected behavior**
I expect the API to give me the accont balance or information on the transaction from the faucet

**Comment by rinor** [comment] 2019-09-28 20:39
Probably your node is not yet fully synced or the transaction that gave you the lovelaces is not included in a block yet.

**Comment by oceanrascal** [comment] 2019-09-28 21:06
> Probably your node is not yet fully synced or the transaction that gave you the lovelaces is not included in a block yet.

hank you for your answer. It has now been only for hours in a fast data center... I checked the generated traffic by jormungandr and it is only around 5 KB/s... when it was syncing it was way higher... I think it is synced by now.

**Comment by embraceitandfaceit** [comment] 2019-09-29 10:45
Hi, do you know how to check when your node is fully synced? Any indication of current blockheight?

**Comment by EndymionJkb** [comment] 2019-09-30 05:36
This shows the blockRecvCnt:

jcli rest v0 node stats get -h "http://127.0.0.1:8443/api" 
(check port - you might be using a different one)

I'm also getting this error, though. I understand it's because the blockchain isn't synced. My problem is it doesn't seem to be syncing at all; just stays at zero. It is running and connected - I can send other commands to it and it answers. It's just not syncing the blockchain, so nothing account-related works.

It says this, then just sits there (an hour so far):

./jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info

Sep 30 00:34:46.860 INFO Starting jormungandr 0.5.2 (HEAD-e7a3efe, release, macos [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Sep 30 00:34:46.861 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Sep 30 00:34:46.861 INFO storing blockchain in '"/tmp/jormungandr/blocks.sqlite"', task: init
Sep 30 00:34:56.410 INFO connecting to bootstrap peer 18.139.40.4:3000, peer_addr: 18.139.40.4:3000, task: bootstrap
Sep 30 00:34:57.528 INFO initial bootstrap completed, peer_addr: 18.139.40.4:3000, task: bootstrap
Sep 30 00:34:57.529 INFO starting task, task: client-query
Sep 30 00:34:57.529 INFO starting task, task: network
Sep 30 00:34:57.529 INFO adding P2P Topology module: trusted-peers, task: network
Sep 30 00:34:57.529 INFO start listening and accepting gRPC connections on 0.0.0.0:3100, task: network
Sep 30 00:34:57.529 INFO Starting 1 workers, scope: global
Sep 30 00:34:57.529 INFO Starting server on 127.0.0.1:8443, scope: global
Sep 30 00:34:57.529 INFO connecting to initial gossip peer, peer_addr: 3.112.185.217:3000, task: network
Sep 30 00:34:57.529 INFO connecting to initial gossip peer, peer_addr: 3.115.57.216:3000, task: network
Sep 30 00:34:57.529 INFO connecting to initial gossip peer, peer_addr: 52.57.157.167:3000, task: network
Sep 30 00:34:57.530 INFO connecting to initial gossip peer, peer_addr: 18.139.40.4:3000, task: network
Sep 30 00:34:57.530 INFO connecting to initial gossip peer, peer_addr: 3.123.177.192:3000, task: network
Sep 30 00:34:57.530 INFO connecting to initial gossip peer, peer_addr: 3.123.155.47:3000, task: network
Sep 30 00:34:57.530 INFO connecting to initial gossip peer, peer_addr: 18.140.134.230:3000, task: network

I've restarted it a couple times. Always says:

jcli rest v0 node stats get -h "http://127.0.0.1:8443/api" 
---
blockRecvCnt: 0
lastBlockDate: "219.37240"
lastBlockFees: 0
lastBlockHash: b5a4b900dabe8f76053107433be48c8c86d261800b11218f0dc4777a49239057
lastBlockHeight: "27273"
lastBlockSum: 0
lastBlockTime: ~
lastBlockTx: 0
txRecvCnt: 0
uptime: 3360

**Comment by jbax** [comment] 2019-09-30 08:45
Same issue for me. Getting error `Account does not exist, scope: global` as well. Exact same thing as reported. Also, the command:

 `./jcli rest v0 node stats get -h  http://127.0.0.1:3101/api`

outputs:

```
blockRecvCnt: 0
lastBlockDate: "220.781"
lastBlockFees: 0
lastBlockHash: c8ce354145f7d2c09ae7b450350969d23a1ae2787888f997f4c5411fd43b326c
lastBlockHeight: "28465"
lastBlockSum: 0
lastBlockTime: ~
lastBlockTx: 0
txRecvCnt: 0
uptime: 1123
```

Other from `uptime`, no other stats change when I re-execute the command every few minutes.

I'm on Manjaro Linux. Here is my system info if it helps:

```
System:    Host: linux-pc Kernel: 4.19.69-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.1.0 Desktop: KDE Plasma 5.16.4 
           Distro: Manjaro Linux 
Machine:   Type: Desktop System: Micro-Star product: MS-7A34 v: 1.0 serial: <filter> 
           Mobo: Micro-Star model: B350 TOMAHAWK (MS-7A34) v: 1.0 serial: <filter> UEFI: American Megatrends v: 1.H0 
           date: 05/02/2018 
Battery:   Device-1: hidpp_battery_0 model: Logitech M705 charge: 90% status: Discharging 
           Device-2: hidpp_battery_1 model: Logitech MK700 charge: 55% (should be ignored) status: Discharging 
CPU:       Topology: 8-Core model: AMD Ryzen 7 1700 bits: 64 type: MT MCP arch: Zen rev: 1 L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 124849 
           Speed: 3121 MHz min/max: N/A Core speeds (MHz): 1: 3121 2: 3126 3: 3122 4: 3136 5: 3125 6: 3130 7: 3126 8: 3127 
           9: 3125 10: 3142 11: 3124 12: 3126 13: 3121 14: 3124 15: 3262 16: 3127 
Graphics:  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 430.40 bus ID: 20:00.0 
           Display: x11 server: X.Org 1.20.5 driver: nvidia resolution: 3440x1440~50Hz, 1920x1080~60Hz 
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 v: 4.6.0 NVIDIA 430.40 direct render: Yes 
Audio:     Device-1: NVIDIA GP104 High Definition Audio driver: snd_hda_intel v: kernel bus ID: 20:00.1 
           Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: Micro-Star MSI driver: snd_hda_intel v: kernel 
           bus ID: 22:00.3 
           Device-3: Corsair type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 3-4:2 
           Sound Server: ALSA v: k4.19.69-1-MANJARO 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI driver: r8168 
           v: 8.047.02-NAPI port: f000 bus ID: 1e:00.0 
           IF: enp30s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 834.62 GiB (89.6%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 850 EVO 1TB size: 931.51 GiB 
Partition: ID-1: / size: 331.49 GiB used: 279.35 GiB (84.3%) fs: ext4 dev: /dev/sda6 
           ID-2: swap-1 size: 4.00 GiB used: 2.39 GiB (59.7%) fs: swap dev: /dev/sda5 
Sensors:   System Temperatures: cpu: 36.1 C mobo: 36.0 C gpu: nvidia temp: 51 C 
           Fan Speeds (RPM): fan-1: 0 fan-2: 1425 fan-3: 708 fan-4: 0 fan-5: 0 fan-6: 0 gpu: nvidia fan: 23% 
           Voltages: 12v: N/A 5v: N/A 3.3v: 3.31 vbat: 3.34 
Info:      Processes: 345 Uptime: 4d 6h 16m Memory: 31.43 GiB used: 9.84 GiB (31.3%) Init: systemd Compilers: gcc: 9.1.0 
           clang: 8.0.1 Shell: bash v: 5.0.9 inxi: 3.0.36 
```

**Comment by dorin100** [comment] 2019-09-30 14:10
duplicate of https://github.com/input-output-hk/jormungandr/issues/860

Some background can be found here - https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60

**Comment by oceanrascal** [comment] 2019-10-02 22:06
All right. Thank you. The problem seems to be solved with the new version upgrade. The reason for the error was an unsynced node.

**Comment by dorin100** [comment] 2019-10-03 05:11
Hi @oceanrascal . Good to know that you were able to progress. There are still issues to be fixed, but the team is working hard.

Is it ok to close this issue?

**Comment by Dmindfuse** [comment] 2019-10-04 17:32
@dorin100 , I upgraded to 0.5.5 and in my case, replaying the instructions still resolves into account issues:

> ~ $ ./startjormungandr 
Oct 04 19:19:17.462 INFO Starting jormungandr 0.5.5 (HEAD-aec29a1, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Oct 04 19:19:17.462 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Oct 04 19:19:17.462 INFO storing blockchain in '"/tmp/jormungandr/blocks.sqlite"', task: init
Oct 04 19:19:17.468 INFO connecting to bootstrap peer 3.123.177.192:3000, peer_addr: 3.123.177.192:3000, task: bootstrap
Oct 04 19:23:46.765 INFO initial bootstrap completed, peer_addr: 3.123.177.192:3000, task: bootstrap
Oct 04 19:23:46.766 INFO starting task, task: client-query
Oct 04 19:23:46.766 INFO starting task, task: network
Oct 04 19:23:46.766 INFO adding P2P Topology module: trusted-peers, task: network
Oct 04 19:23:46.767 INFO start listening and accepting gRPC connections on 0.0.0.0:3100, task: network
Oct 04 19:23:46.767 INFO Starting 1 workers, scope: global
Oct 04 19:23:46.767 INFO Starting server on 127.0.0.1:3101, scope: global
Oct 04 19:23:46.768 INFO connecting to initial gossip peer, peer_addr: 3.112.185.217:3000, task: network
Oct 04 19:23:46.768 INFO connecting to initial gossip peer, peer_addr: 3.115.57.216:3000, task: network
Oct 04 19:23:46.769 INFO connecting to initial gossip peer, peer_addr: 52.57.157.167:3000, task: network
Oct 04 19:23:46.769 INFO connecting to initial gossip peer, peer_addr: 18.139.40.4:3000, task: network
Oct 04 19:23:46.770 INFO connecting to initial gossip peer, peer_addr: 3.123.177.192:3000, task: network
Oct 04 19:23:46.770 INFO connecting to initial gossip peer, peer_addr: 3.123.155.47:3000, task: network
Oct 04 19:23:46.770 INFO connecting to initial gossip peer, peer_addr: 18.140.134.230:3000, task: network
Oct 04 19:25:33.963 WARN Error occurred during request handling: Account does not exist, scope: global
Oct 04 19:25:42.811 WARN Error occurred during request handling: Account does not exist, scope: global
Oct 04 19:25:43.913 WARN Error occurred during request handling: Account does not exist, scope: global
Oct 04 19:28:30.020 WARN Error occurred during request handling: Account does not exist, scope: global
Oct 04 19:30:26.771 WARN Error occurred during request handling: Account does not exist, scope: global
Oct 04 19:30:45.970 WARN Error occurred during request handling: Account does not exist, scope: global
Oct 04 19:31:21.529 WARN Error occurred during request handling: Account does not exist, scope: global

**Comment by Dmindfuse** [comment] 2019-10-04 17:57
@dorin100 , I had the issue as well. I cleaned up my /tmp folder files includnig jormungandr's, restarted a few times and lo and behold I can now query the funds received from the faucet. In my opinion the issue can be closed, but I'd make a note in the instructions that it can take several minutes for the blockchain to sync and show the account stats. (assuming that's what it is)

**Closed** 2019-10-05 07:42 UTC
Labels: duplicate
